### ISSUE TITLE
请问docker run 的时候报错是因为什么呢

### ISSUE THREAD

**Issue by eve0803** [Wyntau/docker-ymfe-yapi#1]
![image](https://user-images.githubusercontent.com/10559224/40166257-b343422e-59f0-11e8-9044-1c4c6f448ce8.png)

**Comment by ik0r** [comment]
@eve0803 
你是运行的哪个image? 

初步怀疑是 docker hub build时, npm 安装并没有完全成功

使用`daocloud.io/wyntau/ymfe-yapi`吧
或者再重新pull一下image, 我又更新了一下

**Comment by ik0r** [comment]
@eve0803 如果没有什么问题, issue就关闭了. 有问题及时反馈
